In [1]:
import pandas as p

In [7]:
data = p.read_csv("cleaned_ecommerce_dataset.csv")
df = p.DataFrame(data)
df

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card,59.98
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,Paypal,89.50
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card,42.75
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card,24.00
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay,50.00
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card,199.99
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card,36.00
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,Paypal,35.50
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card,90.00
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card,49.95
10,ORD-1011,2024-05-03 18:02:00,CUST-511,Los Vegas,USB-C Fast Charging Cable,Electronics,11.99,2,Los Vegas,23.98
11,ORD-1013,2024-06-03 22:15:00,CUST-513,Nyc,Bluetooth Portable Speaker,electronics,49.99,1,Credit Card,49.99
12,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,Credit Card,102000.00
13,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,4,Paypal,90.00
14,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card,99999.00
15,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,30.00,2,Credit Card,60.00

In [8]:
df.shape

(16, 10)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        16 non-null     str
 1   order_datetime  16 non-null     str
 2   customer_id     16 non-null     str
 3   city            16 non-null     str
 4   product_name    16 non-null     str
 5   category        16 non-null     str
 6   cost_per_unit   16 non-null     float64
 7   quantity        16 non-null     int64
 8   payment_method  16 non-null     str
 9   Revenue         16 non-null     float64
dtypes: float64(2), int64(1), str(7)
memory usage: 1.4 KB

In [10]:
df.head()

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card,59.98
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,Paypal,89.50
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card,42.75
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card,24.00
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay,50.00

In [11]:
df.isnull().sum()

order_id          0
order_datetime    0
customer_id       0
city              0
product_name      0
category          0
cost_per_unit     0
quantity          0
payment_method    0
Revenue           0
dtype: int64

In [12]:
df.isnull().sum() / len(df) * 100

order_id          0.0
order_datetime    0.0
customer_id       0.0
city              0.0
product_name      0.0
category          0.0
cost_per_unit     0.0
quantity          0.0
payment_method    0.0
Revenue           0.0
dtype: float64

In [13]:
df = df.dropna()

In [15]:
df["order_id"].duplicated().sum()

np.int64(0)

In [16]:
df = df.drop_duplicates()
df

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card,59.98
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,Paypal,89.50
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card,42.75
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card,24.00
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay,50.00
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card,199.99
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card,36.00
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,Paypal,35.50
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card,90.00
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card,49.95
10,ORD-1011,2024-05-03 18:02:00,CUST-511,Los Vegas,USB-C Fast Charging Cable,Electronics,11.99,2,Los Vegas,23.98
11,ORD-1013,2024-06-03 22:15:00,CUST-513,Nyc,Bluetooth Portable Speaker,electronics,49.99,1,Credit Card,49.99
12,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,Credit Card,102000.00
13,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,4,Paypal,90.00
14,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card,99999.00
15,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,30.00,2,Credit Card,60.00

In [18]:
df.loc[df["cost_per_unit"].idxmax()]

order_id                     ORD-1017
order_datetime    2024-08-03 11:22:00
customer_id                  CUST-517
city                     Philadelphia
product_name      Silicone Phone Case
category                  Electronics
cost_per_unit                 99999.0
quantity                            1
payment_method            Credit Card
Revenue                       99999.0
Name: 14, dtype: object

In [20]:
category_revenue = df.groupby("category")["Revenue"].sum()

category_revenue.sort_values(ascending=False)

category
Apparel           102090.00
Electronics       100372.45
Fitness              150.00
Home Office           95.50
Home & Kitchen        50.00
electronics           49.99
Stationery            49.95
Grocery               42.75
Name: Revenue, dtype: float64