In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("ecommerce_orders_sample.csv")

In [5]:
df = pd.DataFrame(data)

In [6]:
df

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
0,ORD-1001,01-03-2024 09:15,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card
1,ORD-1002,01-03-2024 10:42,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.5,1,PayPal
2,ORD-1003,01-03-2024 12:05,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card
3,ORD-1004,02-03-2024 08:30,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24,1,Credit Card
4,ORD-1005,02-03-2024 14:22,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.5,4,Apple Pay
5,ORD-1006,03-03-2024 11:10,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card
6,ORD-1007,03-03-2024 16:45,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18,2,Debit Card
7,ORD-1008,04-03-2024 09:05,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.5,1,PayPal
8,ORD-1009,04-03-2024 13:37,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45,2,Credit Card
9,ORD-1010,05-03-2024 15:19,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card
10,ORD-1011,05-03-2024 18:02,CUST-511,NaN,USB-C Fast Charging Cable,Electronics,11.99,2,NaN
11,ORD-1002,01-03-2024 10:42,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.5,1,PayPal
12,ORD-1013,06-03-2024 22:15,CUST-513,nyc,Bluetooth Portable Speaker,electronics,49.99,1,CREDIT CARD
13,ORD-1014,06-03-2024 14:20,CUST-514,Phoenix,Wireless Charging Pad,Electronics,$55.00,three,Apple Pay
14,ORD-1015,07-03-2024 09:50,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12,8500,credit Card
15,ORD-1016,07-03-2024 16:35,CUST-516,San Diego,Resistance Bands Set,Fitness,22.5,-4,PayPal
16,ORD-1017,08-03-2024 11:22,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999,1,Credit Card
17,ORD-1018,08-03-2024 17:40,CUST-518,San Jose,NaN,Home & Kitchen,NaN,2,debit CARD
18,ORD-1019,09-03-2024 13:12,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,-15,2,Credit Card
19,ORD-1020,2024-02-31 25:99:00,CUST-520,Columbus,Scented Soy Candle,Home & Kitchen,16,2,Debit Card

In [7]:
df.shape

(20, 9)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        20 non-null     str
 1   order_datetime  20 non-null     str
 2   customer_id     20 non-null     str
 3   city            19 non-null     str
 4   product_name    19 non-null     str
 5   category        20 non-null     str
 6   cost_per_unit   19 non-null     str
 7   quantity        20 non-null     str
 8   payment_method  19 non-null     str
dtypes: str(9)
memory usage: 1.5 KB

In [11]:
df.describe()

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
count,20,20,20,19,19,20,19,20,19
unique,19,19,19,18,18,8,18,8,7
top,ORD-1002,01-03-2024 10:42,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.5,2,Credit Card
freq,2,2,2,2,2,7,2,7,6

In [12]:
df.head()

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
0,ORD-1001,01-03-2024 09:15,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card
1,ORD-1002,01-03-2024 10:42,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.5,1,PayPal
2,ORD-1003,01-03-2024 12:05,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card
3,ORD-1004,02-03-2024 08:30,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24,1,Credit Card
4,ORD-1005,02-03-2024 14:22,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.5,4,Apple Pay

In [13]:
df.tail(3)

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
17,ORD-1018,08-03-2024 17:40,CUST-518,San Jose,NaN,Home & Kitchen,NaN,2,debit CARD
18,ORD-1019,09-03-2024 13:12,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,-15,2,Credit Card
19,ORD-1020,2024-02-31 25:99:00,CUST-520,Columbus,Scented Soy Candle,Home & Kitchen,16,2,Debit Card

In [14]:
df.columns

Index(['order_id', 'order_datetime', 'customer_id', 'city', 'product_name',
       'category', 'cost_per_unit', 'quantity', 'payment_method'],
      dtype='str')

In [15]:
df.isnull().sum()

order_id          0
order_datetime    0
customer_id       0
city              1
product_name      1
category          0
cost_per_unit     1
quantity          0
payment_method    1
dtype: int64

In [16]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [17]:
df[df.duplicated()]

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
11,ORD-1002,01-03-2024 10:42,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.5,1,PayPal

In [41]:
df_no_dup = df.drop_duplicates()
df_no_dup.shape

(19, 9)

In [44]:
df_no_dup["order_datetime"] = pd.to_datetime(df_no_dup["order_datetime"], errors = "coerce")
df_no_dup[["order_id", "order_datetime"]]

    order_id      order_datetime
0   ORD-1001 2024-01-03 09:15:00
1   ORD-1002 2024-01-03 10:42:00
2   ORD-1003 2024-01-03 12:05:00
3   ORD-1004 2024-02-03 08:30:00
4   ORD-1005 2024-02-03 14:22:00
5   ORD-1006 2024-03-03 11:10:00
6   ORD-1007 2024-03-03 16:45:00
7   ORD-1008 2024-04-03 09:05:00
8   ORD-1009 2024-04-03 13:37:00
9   ORD-1010 2024-05-03 15:19:00
10  ORD-1011 2024-05-03 18:02:00
12  ORD-1013 2024-06-03 22:15:00
13  ORD-1014 2024-06-03 14:20:00
14  ORD-1015 2024-07-03 09:50:00
15  ORD-1016 2024-07-03 16:35:00
16  ORD-1017 2024-08-03 11:22:00
17  ORD-1018 2024-08-03 17:40:00
18  ORD-1019 2024-09-03 13:12:00
19  ORD-1020                 NaT

In [45]:
df_no_dup["cost_per_unit"] = pd.to_numeric(df_no_dup["cost_per_unit"], errors = "coerce")
df_no_dup[["order_id", "order_datetime", "cost_per_unit"]]

    order_id      order_datetime  cost_per_unit
0   ORD-1001 2024-01-03 09:15:00          29.99
1   ORD-1002 2024-01-03 10:42:00          89.50
2   ORD-1003 2024-01-03 12:05:00          14.25
3   ORD-1004 2024-02-03 08:30:00          24.00
4   ORD-1005 2024-02-03 14:22:00          12.50
5   ORD-1006 2024-03-03 11:10:00         199.99
6   ORD-1007 2024-03-03 16:45:00          18.00
7   ORD-1008 2024-04-03 09:05:00          35.50
8   ORD-1009 2024-04-03 13:37:00          45.00
9   ORD-1010 2024-05-03 15:19:00           9.99
10  ORD-1011 2024-05-03 18:02:00          11.99
12  ORD-1013 2024-06-03 22:15:00          49.99
13  ORD-1014 2024-06-03 14:20:00            NaN
14  ORD-1015 2024-07-03 09:50:00          12.00
15  ORD-1016 2024-07-03 16:35:00          22.50
16  ORD-1017 2024-08-03 11:22:00       99999.00
17  ORD-1018 2024-08-03 17:40:00            NaN
18  ORD-1019 2024-09-03 13:12:00         -15.00
19  ORD-1020                 NaT          16.00

In [51]:
df_no_dup_no_cost_na = df_no_dup.dropna(subset = ["cost_per_unit", "order_datetime"])
df_no_dup_no_cost_na

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,PayPal
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,PayPal
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card
10,ORD-1011,2024-05-03 18:02:00,CUST-511,NaN,USB-C Fast Charging Cable,Electronics,11.99,2,NaN
12,ORD-1013,2024-06-03 22:15:00,CUST-513,nyc,Bluetooth Portable Speaker,electronics,49.99,1,CREDIT CARD
14,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,credit Card
15,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,-4,PayPal
16,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card
18,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,-15.00,2,Credit Card

In [52]:
df_no_dup_no_cost_na_no_city_na = df_no_dup_no_cost_na.fillna("Los Vegas")
df_no_dup_no_cost_na_no_city_na

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,PayPal
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,PayPal
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card
10,ORD-1011,2024-05-03 18:02:00,CUST-511,Los Vegas,USB-C Fast Charging Cable,Electronics,11.99,2,Los Vegas
12,ORD-1013,2024-06-03 22:15:00,CUST-513,nyc,Bluetooth Portable Speaker,electronics,49.99,1,CREDIT CARD
14,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,credit Card
15,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,-4,PayPal
16,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card
18,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,-15.00,2,Credit Card

In [54]:
df_no_dup_no_cost_na_no_city_na_payment_method_consistent = df_no_dup_no_cost_na_no_city_na
df_no_dup_no_cost_na_no_city_na_payment_method_consistent["payment_method"] = df_no_dup_no_cost_na_no_city_na_payment_method_consistent["payment_method"].str.strip().str.title()
df_no_dup_no_cost_na_no_city_na_payment_method_consistent[["order_id", "payment_method"]]

    order_id payment_method
0   ORD-1001    Credit Card
1   ORD-1002         Paypal
2   ORD-1003     Debit Card
3   ORD-1004    Credit Card
4   ORD-1005      Apple Pay
5   ORD-1006    Credit Card
6   ORD-1007     Debit Card
7   ORD-1008         Paypal
8   ORD-1009    Credit Card
9   ORD-1010     Debit Card
10  ORD-1011      Los Vegas
12  ORD-1013    Credit Card
14  ORD-1015    Credit Card
15  ORD-1016         Paypal
16  ORD-1017    Credit Card
18  ORD-1019    Credit Card

In [57]:
def revise_cost_per_unit(amount):
    if amount < 0:
        return (-amount) + 15
    return amount

def revise_quantity(count):
    if count < 0:
        return -count
    return count

In [60]:
df_revised_cost_and_quantity = df_no_dup_no_cost_na_no_city_na_payment_method_consistent
df_revised_cost_and_quantity["cost_per_unit"] = df_revised_cost_and_quantity["cost_per_unit"].apply(revise_cost_per_unit)

df_revised_cost_and_quantity["quantity"] = pd.to_numeric(df_revised_cost_and_quantity["quantity"])
df_revised_cost_and_quantity["quantity"] = df_revised_cost_and_quantity["quantity"].apply(revise_quantity)
df_revised_cost_and_quantity[["order_id", "cost_per_unit", "quantity"]]

    order_id  cost_per_unit  quantity
0   ORD-1001          29.99         2
1   ORD-1002          89.50         1
2   ORD-1003          14.25         3
3   ORD-1004          24.00         1
4   ORD-1005          12.50         4
5   ORD-1006         199.99         1
6   ORD-1007          18.00         2
7   ORD-1008          35.50         1
8   ORD-1009          45.00         2
9   ORD-1010           9.99         5
10  ORD-1011          11.99         2
12  ORD-1013          49.99         1
14  ORD-1015          12.00      8500
15  ORD-1016          22.50         4
16  ORD-1017       99999.00         1
18  ORD-1019          30.00         2

In [61]:
df_clean = df_revised_cost
df_clean["Revenue"] = df_clean["quantity"] * df_clean["cost_per_unit"]
df_clean

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card,59.98
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,Paypal,89.50
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card,42.75
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card,24.00
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay,50.00
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card,199.99
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card,36.00
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,Paypal,35.50
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card,90.00
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card,49.95
10,ORD-1011,2024-05-03 18:02:00,CUST-511,Los Vegas,USB-C Fast Charging Cable,Electronics,11.99,2,Los Vegas,23.98
12,ORD-1013,2024-06-03 22:15:00,CUST-513,Nyc,Bluetooth Portable Speaker,electronics,49.99,1,Credit Card,49.99
14,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,Credit Card,102000.00
15,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,4,Paypal,90.00
16,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card,99999.00
18,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,30.00,2,Credit Card,60.00

In [64]:
Q1 = df_clean["quantity"].quantile(0.25)
Q3 = df_clean["quantity"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("lower_limit = ", lower_limit)
print("upper_limit = ", upper_limit)

lower_limit =  -2.375
upper_limit =  6.625

In [65]:
df_clean[df_clean["quantity"] > upper_limit]

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
14,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.0,8500,Credit Card,102000.0

In [66]:
df_clean

,order_id,order_datetime,customer_id,city,product_name,category,cost_per_unit,quantity,payment_method,Revenue
0,ORD-1001,2024-01-03 09:15:00,CUST-501,Chicago,Wireless Ergonomic Mouse,Electronics,29.99,2,Credit Card,59.98
1,ORD-1002,2024-01-03 10:42:00,CUST-502,Seattle,Mechanical Keyboard,Electronics,89.50,1,Paypal,89.50
2,ORD-1003,2024-01-03 12:05:00,CUST-503,Austin,Organic Green Tea (Pack of 50),Grocery,14.25,3,Debit Card,42.75
3,ORD-1004,2024-02-03 08:30:00,CUST-504,Denver,Yoga Mat Non-Slip,Fitness,24.00,1,Credit Card,24.00
4,ORD-1005,2024-02-03 14:22:00,CUST-505,Boston,Ceramic Coffee Mug 12oz,Home & Kitchen,12.50,4,Apple Pay,50.00
5,ORD-1006,2024-03-03 11:10:00,CUST-506,San Francisco,Noise Cancelling Headphones,Electronics,199.99,1,Credit Card,199.99
6,ORD-1007,2024-03-03 16:45:00,CUST-507,Atlanta,Stainless Steel Water Bottle,Fitness,18.00,2,Debit Card,36.00
7,ORD-1008,2024-04-03 09:05:00,CUST-508,Portland,LED Desk Lamp with USB Port,Home Office,35.50,1,Paypal,35.50
8,ORD-1009,2024-04-03 13:37:00,CUST-509,Miami,Polarized Sunglasses UV400,Apparel,45.00,2,Credit Card,90.00
9,ORD-1010,2024-05-03 15:19:00,CUST-510,Dallas,Hardcover Ruled Notebook,Stationery,9.99,5,Debit Card,49.95
10,ORD-1011,2024-05-03 18:02:00,CUST-511,Los Vegas,USB-C Fast Charging Cable,Electronics,11.99,2,Los Vegas,23.98
12,ORD-1013,2024-06-03 22:15:00,CUST-513,Nyc,Bluetooth Portable Speaker,electronics,49.99,1,Credit Card,49.99
14,ORD-1015,2024-07-03 09:50:00,CUST-515,Houston,Cotton Crew Socks (3-Pack),Apparel,12.00,8500,Credit Card,102000.00
15,ORD-1016,2024-07-03 16:35:00,CUST-516,San Diego,Resistance Bands Set,Fitness,22.50,4,Paypal,90.00
16,ORD-1017,2024-08-03 11:22:00,CUST-517,Philadelphia,Silicone Phone Case,Electronics,99999.00,1,Credit Card,99999.00
18,ORD-1019,2024-09-03 13:12:00,CUST-519,Nashville,Adjustable Laptop Stand,Home Office,30.00,2,Credit Card,60.00

In [70]:
df_clean.to_csv("cleaned_ecommerce_dataset.csv", index = False)